### PR TITLE
add special chars support for RPC login/password (e.g. @,",%,)

### PR DESCRIPTION
**Pull request by shaman**

### CODE REVIEW

**Comment by aceat64** [comment]
I like the idea, but I don't think we should be doing an html_entity_decode() on the username and password. It should be up to the user/dev to pass us the correct info.

**Comment by shaman** [comment]
your argument is right, it looks not laconically, but some user requests/frameworks/scripts may give raw encoded data from the database, for example. what we lose with html_entity_decode() anyway?

**Comment by aceat64** [comment]
It doesn't work if their password is:

> y5xo&lt;zjnl

We would end up "decoding" it to:

> y5xo<zjnl

**Comment by aceat64** [comment]
Thanks @shaman :)

**Pull request merged**
